version: '3.4'
services:
  jsonhound:
    image: jsonhound
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/opt
    working_dir: /opt
    entrypoint:
      - perl6
      - -Ilib
      - bin/jsonhound
    
